POST http://localhost:8080/events
content-type: application/application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvbkB0ZXN0My5jb20iLCJleHAiOjE3NjQzNTg5NTQsInVzZXJJZCI6MX0.TT0xqLLVQB8UxoMzkloMXbc03ApKN_CIJ2selxcQKVw

{
  "name": "test event234234234",
  "description": "a test event",
  "location": "test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
} 