POST http://localhost:8080/events
content-type: application/application/json

{
  "name": "test event",
  "description": "a test event",
  "location": "test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
} 